### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by leowinner77** [maxlit/pyEdgeworthBox#3]
Hi, good afternoon, I'm an economics student from the fifth semester, and im needing a program to graph an edgeworth box with 2 different utilities functions, with each consumer having its own prefferences for goods. I'm going to be honest here, I don't know anything about coding or how to use python, I've tried to run the code, but I've got a couple errors while running the example. If you could guide me on how to use this, I'd be really grateful.

**Comment by maxlit** [comment]
https://github.com/maxlit/pyEdgeworthBox#how-to-use-it
